AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM template

Resources:
  RegisterCompanyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Handler: dist/lambda/register-company.handler
      CodeUri: .
      MemorySize: 128
      Timeout: 10
